version: '2'

services:
  reverse-proxy-test-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/reserve-proxy-test:latest
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logrotate.conf:/etc/logrotate.conf
    environment:
      TZ: Asia/Seoul
    links:
      - mauve-test-container
    depends_on:
      - mauve-test-container
  mauve-test-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/mauve-test:latest
    build:
      context: ./app
    ports:
      - '3000:3000'
      - '3030:3030'
    networks:
      - default
