version: '2'

services:
  agent:
      container_name: newrelic-infra
      build:
        context: ./newrelic-infra-setup
        dockerfile: ./newrelic-infra.dockerfile
      cap_add:
        - SYS_PTRACE
      network_mode: host
      pid: host
      privileged: true
      environment:
        NEW_RELIC_NO_CONFIG_FILE : true
        NEW_RELIC_DISTRIBUTED_TRACING_ENABLED : true
        NEW_RELIC_LOG: stdout
      volumes:
        - "/:/host:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
      restart: unless-stopped
  reverse-proxy-test-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/reserve-proxy-test:latest
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logrotate.conf:/etc/logrotate.conf
    environment:
      TZ: Asia/Seoul
    external_links:
      - mauve-test-container
  mauve-test-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/mauve-test:latest
    build:
      context: ./app
    ports:
      - '3000:3000'
      - '3030:3030'
    networks:
      - default
